config/routes.rb
App4::Application.routes.draw do
  
  root :to =>"galleries#index"
  resources :galleries

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
 #specify that the avatar is a paperclip file attachment
  #specify additional styles that you want to use in views or eslewhere
  has_attached_file :picture, :styles => {:thumb => "100x200>"}
  validates :picture, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :picture
  
  #or use helper style validations
  validates_attachment_content_type :picture, 
                                      :content_type => /^image\/(png|gif|jpeg)/,
                                      :message => 'only (png/gif/jpeg) images'
  validates_attachment_size :picture,  :in => 0..1024.kilobytes  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @gallery = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end
   
   def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to action: 'index', notice: 'User was successfully created.'
    else
      render action: 'new', alert: 'User could not be created' 
    end
  end
  
   def update
     @gallery = Gallery.find_by_id(params[:id])
      if @gallery.update(gallery_params)
      flash[:notice] = "Success Update Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
  end
  
  def edit
    @gallery = Gallery.find_by_id(params[:id])
   
  end
  
  def destroy
     @gallery = Gallery.find_by_id(params[:id])
      if @gallery.destroy
      flash[:notice] = "Success Delete a Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :content, :picture)
    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_navigation.html.erb
<!--bagian navigation-->
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href=”#” class = "navbar-brand">Implement CRUD For Image</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",galleries_path%></li>
            <li><%= link_to "Create",new_gallery_path%></li>
            <li><a href=”#”>Contact</a></li>
          </ul>
        </div>  
      </div>
    </div>
    <br>
    <br/>
    <br>
    <br/>

app/views/galleries/edit.html.erb
<%= render 'navigation'%>
<%= form_for @gallery, :html => { :multipart => true } do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= @gallery.errors[:title].first unless @gallery.errors[:title].blank? %>
<br/>
<%= f.label :content %>
<%= f.text_area :content, cols: 20, rows: 10 %>
<%= @gallery.errors[:content].first unless @gallery.errors[:content].blank? %>
<br/>
<%= f.label :picture %>
<%= f.file_field :picture %></p>

<%= f.submit:submit %>
<% end %>

app/views/galleries/index.html.erb
<%= render 'navigation'%>

	<% @gallery.each do |gallery| %>
    <div class="gallery"><%= link_to image_tag(gallery.picture.url(:thumb)),gallery.picture.url(:original), class: "fancybox"%>
	<div class="title"><%= gallery.title %>
    <div class="content"><%= gallery.content %>
    	
    	</div>
    	</div>
    	<span><%= link_to 'EDIT', edit_gallery_path(gallery.id) %></span>
    	<span><%= link_to 'REMOVE', gallery_path(gallery.id),method: "DELETE", data: {confirm: 'Delete this data'} %></span>
    	</div>
    
    
    
    <%end%>

app/views/galleries/new.html.erb
<%= render 'navigation'%>
<%= form_for @gallery, :html => { :multipart => true } do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= @gallery.errors[:title].first unless @gallery.errors[:title].blank? %>
<br/>
<%= f.label :content %>
<%= f.text_area :content, cols: 20, rows: 10 %>
<%= @gallery.errors[:content].first unless @gallery.errors[:content].blank? %>
<br/>
<%= f.label :picture %>
<%= f.file_field :picture %></p>

<%= f.submit:submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>